/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cisco_fibnative_FibLib */

#ifndef _Included_com_cisco_fibnative_FibLib
#define _Included_com_cisco_fibnative_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cisco_fibnative_FibLib
 * Method:    fibN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_cisco_fibnative_FibLib_fibN
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
